---
- hosts: webservers
  become: yes
  tasks:
  - name:  install webserver on Ubuntu(apache2)
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"

  - name: install websrver on Redhat(httpd)
    yum:
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"