---
- hosts: webservers
  become: yes
  tasks:
  - name:  install webserver on Ubuntu(apache2)
    apt:
      name: "{{webserverUbuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  - name: start webserver on Ubuntu(apache2)
    service: 
      name: "{{webserverUbuntu}}"
      state: started
    when: ansible_os_family =="Debian"
  
  - name: install webserver on redhat (httpd)
    yum:
      name: "{{webserverRedhat}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: start webserver on redhat
    service:
      name: "{{webserverRedhat}}"
      state: started
    when: ansible_os_family =="RedHat"