---
- hosts: all
  become: yes
  tasks:

  - name: install WS on ubuntu-apache2
    apt:
      name: apache2
      state: present
  - name: run ubuntu-apache2
    service:
       name: apache2
       state: started
    when: ansible_os_family =="Debian"

  - name: install WS on redhat-httpd
    yum:
      name: httpd
      state: present
  - name: run WS on redhat-httpd
    service:
       name: httpd
       state: started
  when: ansible_os_family =="RedHat"
