---
- hosts: all
  become: yes
  tasks:
  - name: install WS on ubuntu-apache2
    apt:
      name: apache2
      state: present
  - name: run ubuntu-apache2
    service:
       name: apache2
       state: started
